### ISSUE TITLE
ABuild

### ISSUE THREAD

**Issue by Paribu-zz** [kenoma/adaptive-neuro-fuzzy#1]
Hello,

The class ABuilder is used to create a new IS but I can not find a definition of the class at anywhere in the code.

ANFIS fis = ABuilder<GaussianRule>.Build(x, y, extractor, bprop, 1000);

Is some code still missing in the project?

Best regards,
Patrick

**Comment by kenoma** [comment]
Hello Patrick,

Thank you for interest to this project. I have added missing file to the project.

Best regards,
Yury.
