### ISSUE TITLE
I want to know Manual Mechanism this ANFIS

### ISSUE THREAD

**Issue by alifatic** [kenoma/adaptive-neuro-fuzzy#3]
may i know the manual mechanism or flow of this project? i try to read theory of anfis but i cannot match with every part of your code, i still dont understand,
thanks for your amazing code

**Comment by kenoma** [comment]
Hi! I'm not sure that I understand meaning of _manual mechanism_ in context to this project. I was inspired by[ this lecture notes](http://uni-obuda.hu/users/fuller.robert/dam.pdf) when started to develop this ANFIS. Hope, it will make clear some moments in my realization.
